package com.techfree.enums;

public enum TipoLog {
    CRIACAO_DE_PROJETO,
    PROJETO_EM_ANDAMENTO,
    PROJETO_ATUALIZADO,
    PROJETO_FINALIZADO,
    PROJETO_EM_REVISAO,
    PROJETO_CANCELADO,
    FREELANCER_SELECIONADO,
    CONVITE_ENVIADO,
    CERTIFICADO_DE_CONCLUSAO,
    CANDIDATURA_ENVIADA,
    CANDIDATURA_RECUSADA,
    FEEDBACK_DE_FREELANCER,
    FEEDBACK_DE_EMPRESA,
    LOGIN,
    REGISTRO_EMPRESA,
    REGISTRO_FREELANCER,
    RECUPERACAO_DE_SENHA,
    REDEFINICAO_DE_SENHA,
    ATUALIZACAO_PERFIL_FREELANCER,
    ATUALIZACAO_PERFIL_EMPRESA,
    ATUALIZACAO_EMAIL_FREELANCER,
    ATUALIZACAO_SENHA_FREELANCER,
    ATUALIZACAO_EMAIL_EMPRESA,
    ATUALIZACAO_SENHA_EMPRESA,
    UPLOAD_DE_ASSINATURA
}
