version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: techfree-mysql
    restart: always
    environment:
      MYSQL_DATABASE: techfree_db
      MYSQL_ROOT_PASSWORD: F@tec123
    ports:
      - "3308:3308"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: techfree-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/techfree_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: F@tec123
    ports:
      - "8082:8082"
    volumes:
      - ./src/main/resources/uploads:/app/uploads
    restart: always

volumes:
  db_data:
